services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.prod
        container_name: portfolio
        working_dir: /app
        ports:
            - "3000"
        environment:
            - NODE_ENV=production
            - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
            - NEXT_PUBLIC_EMAIL=${NEXT_PUBLIC_EMAIL}
            - NEXT_PUBLIC_SANITY_PROJECT_ID=${NEXT_PUBLIC_SANITY_PROJECT_ID}
            - NEXT_PUBLIC_SANITY_DATASET=${NEXT_PUBLIC_SANITY_DATASET}
            - NEXT_PUBLIC_SANITY_API_VERSION=${NEXT_PUBLIC_SANITY_API_VERSION}
            - NODE_OPTIONS=--dns-result-order=ipv4first --max-old-space-size=768
        command: ["npm", "start"]
        restart: unless-stopped
        dns:
            - 8.8.8.8
            - 1.1.1.1
        dns_opt:
            - ndots:1
            - timeout:2
            - attempts:3
        sysctls:
            - net.ipv4.ip_local_port_range=1024 65535
            - net.ipv4.tcp_tw_reuse=1
        networks:
            - traefik-public
        
        deploy:
            resources:
                limits:
                    memory: 1G
                    cpus: '1'
                reservations:
                    memory: 512M
                    cpus: '0.5'
        
        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.portfolio.rule=Host(`piedanna.dev`)"
            - "traefik.http.routers.portfolio.entrypoints=websecure"
            - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt"
            - "traefik.http.services.portfolio.loadbalancer.server.port=3000"
            - "traefik.http.services.portfolio.loadbalancer.healthcheck.path=/api/health"
            - "traefik.http.services.portfolio.loadbalancer.healthcheck.interval=30s"
            - "traefik.http.services.portfolio.loadbalancer.healthcheck.timeout=10s"
            - "traefik.docker.network=traefik-public"

networks:
    traefik-public:
        external: true