services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    container_name: portfolio
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: ["npm", "start"]