import { defineType, defineField } from 'sanity'

export default defineType({
  name: 'staticTexts',
  title: 'Tous les Textes Statiques',
  type: 'document',
  fields: [
    // === HERO SECTION ===
    defineField({
      name: 'heroTitle',
      title: 'Hero - Titre',
      type: 'string',
      initialValue: 'Développeur Web Freelance',
      group: 'hero',
    }),
    defineField({
      name: 'heroSubtitle',
      title: 'Hero - Sous-titre',
      type: 'text',
      rows: 3,
      initialValue: 'Je crée des sites web performants qui convertissent vos visiteurs en clients',
      group: 'hero',
    }),
    defineField({
      name: 'heroDescription',
      title: 'Hero - Description',
      type: 'text',
      rows: 4,
      initialValue: 'Sites vitrine, e-commerce, applications web : je développe votre projet digital de A à Z. Tarifs transparents, accompagnement personnalisé, résultats garantis.',
      group: 'hero',
    }),
    defineField({
      name: 'heroCtaPrimary',
      title: 'Hero - Bouton Principal',
      type: 'string',
      initialValue: 'Démarrer Mon Projet',
      group: 'hero',
    }),
    defineField({
      name: 'heroCtaSecondary',
      title: 'Hero - Bouton Secondaire',
      type: 'string',
      initialValue: 'Découvrir Mes Services',
      group: 'hero',
    }),
    defineField({
      name: 'heroAvailabilityText',
      title: 'Hero - Texte Disponibilité',
      type: 'string',
      initialValue: 'Disponible pour nouveaux projets',
      group: 'hero',
    }),

    // === PROBLEMES SECTION ===
    defineField({
      name: 'problemesTitle',
      title: 'Problèmes - Titre',
      type: 'string',
      initialValue: 'Pourquoi Faire Appel à un <span class="gradient">Développeur Web Freelance</span> ?',
      group: 'problemes',
    }),
    defineField({
      name: 'problemesDescription',
      title: 'Problèmes - Description',
      type: 'text',
      rows: 3,
      initialValue: 'Créer un <strong>site internet professionnel</strong> peut vite devenir un casse-tête : agences web hors de prix, prestataires peu réactifs, résultats décevants. En tant que <strong>développeur freelance indépendant</strong>, je vous offre une alternative efficace et abordable.',
      group: 'problemes',
    }),

    // === SOLUTIONS SECTION ===
    defineField({
      name: 'solutionsTitle',
      title: 'Solutions - Titre',
      type: 'string',
      initialValue: 'Un Développeur Web Freelance qui Comprend Vos <span class="gradient">Besoins Business</span>',
      group: 'solutions',
    }),
    defineField({
      name: 'solutionsDescription',
      title: 'Solutions - Description',
      type: 'text',
      rows: 3,
      initialValue: 'Je suis <strong>Hugo</strong>, <strong>développeur web freelance</strong> spécialisé dans la <strong>création de sites internet performants</strong>. Mon approche ? Des <strong>sites web professionnels</strong> conçus pour atteindre vos objectifs : générer des leads, vendre en ligne, ou simplement renforcer votre crédibilité.',
      group: 'solutions',
    }),
    defineField({
      name: 'solutionsCta',
      title: 'Solutions - Bouton',
      type: 'string',
      initialValue: 'Parlons de Votre Projet',
      group: 'solutions',
    }),

    // === OFFERS SECTION ===
    defineField({
      name: 'offersTitle',
      title: 'Services - Titre',
      type: 'string',
      initialValue: 'Services de <span class="gradient">Développement Web</span>',
      group: 'offers',
    }),
    defineField({
      name: 'offersDescription',
      title: 'Services - Description',
      type: 'string',
      initialValue: 'Des services adaptés à vos besoins et votre budget',
      group: 'offers',
    }),
    defineField({
      name: 'offersTtcLabel',
      title: 'Services - Label TTC',
      type: 'string',
      initialValue: 'TTC',
      group: 'offers',
    }),
    defineField({
      name: 'offersIdealForLabel',
      title: 'Services - Label Idéal pour',
      type: 'string',
      initialValue: 'Idéal pour :',
      group: 'offers',
    }),
    defineField({
      name: 'offersOnQuoteLabel',
      title: 'Services - Label Sur devis',
      type: 'string',
      initialValue: 'Sur devis',
      group: 'offers',
    }),

    // === PROJECTS SECTION ===
    defineField({
      name: 'projectsTitle',
      title: 'Projets - Titre',
      type: 'string',
      initialValue: 'Projets <span class="gradient">Récents</span>',
      group: 'projects',
    }),
    defineField({
      name: 'projectsDescription',
      title: 'Projets - Description',
      type: 'text',
      rows: 2,
      initialValue: 'Découvrez mes <strong>réalisations</strong> : sites vitrine, e-commerce et applications web',
      group: 'projects',
    }),
    defineField({
      name: 'projectsUnavailableText',
      title: 'Projets - Texte indisponible',
      type: 'string',
      initialValue: '(Site actuellement indisponible)',
      group: 'projects',
    }),
    defineField({
      name: 'projectsViewText',
      title: 'Projets - Texte voir projet',
      type: 'string',
      initialValue: 'Voir le projet →',
      group: 'projects',
    }),

    // === PROCESS SECTION ===
    defineField({
      name: 'processTitle',
      title: 'Processus - Titre',
      type: 'string',
      initialValue: 'Comment On <span class="gradient">Travaille Ensemble</span> ?',
      group: 'process',
    }),
    defineField({
      name: 'processDescription',
      title: 'Processus - Description',
      type: 'string',
      initialValue: 'Un process simple et transparent, de l\'idée à la mise en ligne',
      group: 'process',
    }),
    defineField({
      name: 'processCta',
      title: 'Processus - Bouton',
      type: 'string',
      initialValue: 'Commençons par un échange gratuit',
      group: 'process',
    }),

    // === FAQ SECTION ===
    defineField({
      name: 'faqTitle',
      title: 'FAQ - Titre',
      type: 'string',
      initialValue: 'Questions <span class="gradient">Fréquentes</span>',
      group: 'faq',
    }),
    defineField({
      name: 'faqDescription',
      title: 'FAQ - Description',
      type: 'string',
      initialValue: 'Tout ce que vous devez savoir sur mes services',
      group: 'faq',
    }),

    // === CONTACT SECTION ===
    defineField({
      name: 'contactTitle',
      title: 'Contact - Titre',
      type: 'string',
      initialValue: 'Prêt à Lancer Votre <span class="gradient">Projet</span> ?',
      group: 'contact',
    }),
    defineField({
      name: 'contactDescription',
      title: 'Contact - Description',
      type: 'string',
      initialValue: 'Contactez-moi directement par le canal qui vous convient. Je vous réponds sous 24h.',
      group: 'contact',
    }),
    defineField({
      name: 'contactLinkedinTitle',
      title: 'Contact - Titre LinkedIn',
      type: 'string',
      initialValue: 'LinkedIn',
      group: 'contact',
    }),
    defineField({
      name: 'contactLinkedLink',
      title: 'Contact - Lien LinkedIn',
      type: 'url',
      group: 'contact',
    }),
    defineField({
      name: 'contactLinkedinSubtext',
      title: 'Contact - Sous-texte LinkedIn',
      type: 'string',
      initialValue: 'Pour un contact professionnel',
      group: 'contact',
    }),
    defineField({
      name: 'contactLinkedinCta',
      title: 'Contact - CTA LinkedIn',
      type: 'string',
      initialValue: 'Me contacter sur LinkedIn →',
      group: 'contact',
    }),
    defineField({
      name: 'contactEmailTitle',
      title: 'Contact - Titre Email',
      type: 'string',
      initialValue: 'Email',
      group: 'contact',
    }),
    defineField({
      name: 'contactEmail',
      title: 'Contact - Email',
      type: 'email',
      group: 'contact',
    }),
    defineField({
      name: 'contactEmailSubtext',
      title: 'Contact - Sous-texte Email',
      type: 'string',
      initialValue: 'Pour une demande détaillée',
      group: 'contact',
    }),
    defineField({
      name: 'contactPhoneTitle',
      title: 'Contact - Titre Téléphone',
      type: 'string',
      initialValue: 'Téléphone',
      group: 'contact',
    }),
    defineField({
      name: 'contactPhone',
      title: 'Contact - Téléphone',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactPhoneSubtext',
      title: 'Contact - Sous-texte Téléphone',
      type: 'string',
      initialValue: 'Pour un échange rapide',
      group: 'contact',
    }),
    defineField({
      name: 'contactPhoneButtonText',
      title: 'Contact - Texte bouton téléphone',
      type: 'string',
      initialValue: 'Afficher le numéro →',
      group: 'contact',
    }),
    defineField({
      name: 'contactLocationDescription',
      title: 'Contact - Description localisation',
      type: 'text',
      rows: 3,
      initialValue: 'J\'interviens sur Toulouse, Haute-Garonne et toute la France en télétravail. Disponibilité pour des rendez-vous en visio ou en présentiel selon votre localisation.',
      group: 'contact',
    }),
    defineField({
      name: 'contactAvailabilityLabel',
      title: 'Contact - Label Disponibilité',
      type: 'string',
      initialValue: 'Disponibilité',
      group: 'contact',
    }),
    defineField({
      name: 'contactLocation',
      title: 'Contact - Localisation',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'availabilityDays',
      title: 'Contact - Disponibilité Jours',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'availabilityHours',
      title: 'Contact - Disponibilité Heures',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactBadge1',
      title: 'Contact - Badge 1',
      type: 'string',
      initialValue: 'Premier échange gratuit',
      group: 'contact',
    }),
    defineField({
      name: 'contactBadge2',
      title: 'Contact - Badge 2',
      type: 'string',
      initialValue: 'Réponse sous 24h',
      group: 'contact',
    }),
    defineField({
      name: 'contactBadge3',
      title: 'Contact - Badge 3',
      type: 'string',
      initialValue: 'Sans engagement',
      group: 'contact',
    }),

    // === HEADER ===
    defineField({
      name: 'headerLogoText',
      title: 'Header - Texte Logo',
      type: 'string',
      initialValue: 'Hugo Piedanna',
      group: 'header',
    }),
    defineField({
      name: 'headerLogoTextMobile',
      title: 'Header - Texte Logo Mobile',
      type: 'string',
      initialValue: 'Hugo P.',
      group: 'header',
    }),
    defineField({
      name: 'headerCtaButton',
      title: 'Header - Bouton CTA',
      type: 'string',
      initialValue: 'Démarrer mon projet',
      group: 'header',
    }),

    // === FOOTER ===
    defineField({
      name: 'footerTitle',
      title: 'Footer - Titre',
      type: 'string',
      initialValue: 'Hugo Piedanna',
      group: 'footer',
    }),
    defineField({
      name: 'footerDescription1',
      title: 'Footer - Description ligne 1',
      type: 'string',
      initialValue: 'Développeur web freelance basé à Toulouse.',
      group: 'footer',
    }),
    defineField({
      name: 'footerDescription2',
      title: 'Footer - Description ligne 2',
      type: 'string',
      initialValue: 'Création de sites professionnels pour TPE et PME.',
      group: 'footer',
    }),
    defineField({
      name: 'footerLegalTitle',
      title: 'Footer - Titre Légal',
      type: 'string',
      initialValue: 'Légal',
      group: 'footer',
    }),
    defineField({
      name: 'footerCguLabel',
      title: 'Footer - Label CGU',
      type: 'string',
      initialValue: 'CGU',
      group: 'footer',
    }),
    defineField({
      name: 'footerPrivacyLabel',
      title: 'Footer - Label Confidentialité',
      type: 'string',
      initialValue: 'Confidentialité',
      group: 'footer',
    }),
    defineField({
      name: 'footerCgvLabel',
      title: 'Footer - Label CGV',
      type: 'string',
      initialValue: 'CGV',
      group: 'footer',
    }),
    defineField({
      name: 'footerCopyright',
      title: 'Footer - Copyright',
      type: 'string',
      initialValue: 'Hugo Piedanna - Développeur web freelance • Fait avec ❤️',
      group: 'footer',
    }),
  ],
  groups: [
    { name: 'hero', title: 'Hero' },
    { name: 'problemes', title: 'Problèmes' },
    { name: 'solutions', title: 'Solutions' },
    { name: 'offers', title: 'Services' },
    { name: 'projects', title: 'Projets' },
    { name: 'process', title: 'Processus' },
    { name: 'faq', title: 'FAQ' },
    { name: 'contact', title: 'Contact' },
    { name: 'header', title: 'Header' },
    { name: 'footer', title: 'Footer' },
  ],
})
